[package]
name = "kalman"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "inversion"
harness = false

[[bench]]
name = "mult"
harness = false

[dev-dependencies]
assert_float_eq = "1.1.3"
criterion = "0.5.1"

[dependencies]
stdint = "0.2.0"
